Refactor cli identification
jo-jstrm/SmartHomeBuddy pull request #104
Opened 2022-09-20 18:31 UTC by TB-DevAcc

Changed some aesthetics and refactored the identification function.

Works with the simple dummy pcap.

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/25723425/191336577-2c6df738-b7ee-40eb-bf26-b4b23f472aed.png">

2022-09-27 14:02 UTC, TB-DevAcc commented
Works now with a bigger pcap and different measurements.

2022-09-29 08:11 UTC, jo-jstrm requested changes
We currently run into an error when training a model or identifying a device. This error is most likely not caused by this PR, but it exists anyways.

```bash
(.venv) jo@pop-os:~/git/SmartHomeBuddy$ shbdeviceidentifier -d train --measurement "test" "rf"
   ____               __  __ __               ___          __   __    
  / __/_ _  ___ _____/ /_/ // /__  __ _  ___ / _ )__ _____/ /__/ /_ __
 _\ \/  ' \/ _ `/ __/ __/ _  / _ \/  ' \/ -_) _  / // / _  / _  / // /
/___/_/_/_/\_,_/_/  \__/_//_/\___/_/_/_/\__/____/\_,_/\_,_/\_,_/\_, / 
                                                               /___/  

10:08:46 | start_database:22              | [  DEBUG  ] SHB_HOME: /home/jo/git/SmartHomeBuddy
10:08:46 | start_database:23              | [  DEBUG  ] DATA_DIR: /home/jo/git/SmartHomeBuddy/device-identifier/shbdeviceidentifier
10:08:46 | start_InfluxDB:404             | [  DEBUG  ] InfluxDB started successfully.
10:08:46 | _create_SQLite_tables:241      | [  DEBUG  ] Table 'users' created successfully.
10:08:46 | _create_SQLite_tables:244      | [  DEBUG  ] Table 'influxdb' created successfully.
10:08:46 | _create_SQLite_tables:247      | [  DEBUG  ] Table 'devices' created successfully.
10:08:46 | _create_SQLite_tables:250      | [  DEBUG  ] Table 'context' created successfully.
10:08:46 | _get_InfluxDB_connection:259   | [  DEBUG  ] Connected to InfluxDB v2.3.0+SNAPSHOT.090f681737 at localhost:8086.
10:08:46 | is_connected:323               | [  DEBUG  ] Databases are connected.
10:08:46 | invoke:760                     | [  DEBUG  ] Entering 'train' (args=(), kwargs={'measurement': 'test', 'model_name': 'rf'})
10:08:46 | train:141                      | [  DEBUG  ] Querying train data in time range 1970-01-01 00:00:00 - 2022-09-29 10:08:46.748096.
10:08:46 | get_influxdb_client:335        | [  DEBUG  ] Creating InfluxDBClient with the following params: url=http://localhost:8086, org=SmartHomeBuddy, token=_MKqs-OXmIYgqg0Q9PwFA3sH_oW2oyX1ZWxnRcUxs7mnpwbHo8PviMIbv6mJnDq2eEIwGnEl2h1rrOMxL7Lc0g==
10:08:46 | _from_influxdb:42              | [  INFO   ] Loading data from measurement 'test'. Depending on the size of the data this might take a while.
✅  Finished loading data from InfluxDB.
10:08:46 | _from_influxdb:53              | [  DEBUG  ] Loaded 13 rows from InfluxDB.
10:08:46 | from_database:170              | [  DEBUG  ] Devices: [('Desktop', '192.168.178.41'), ('', '192.168.178.42'), ('Google-Nest-Mini', '192.168.178.44'), ('Google-Nest-Mini', '192.168.178.45'), ('ESP-1DC41C', '192.168.178.47'), ('', '50.16.7.188'), ('fritz.box', '192.168.178.1')]
10:08:46 | from_database:175              | [  DEBUG  ] ip_to_label_map: {'192.168.178.41': 'Desktop', '192.168.178.42': '', '192.168.178.44': 'Google-Nest-Mini', '192.168.178.45': 'Google-Nest-Mini', '192.168.178.47': 'ESP-1DC41C', '50.16.7.188': '', '192.168.178.1': 'fritz.box'}
10:08:46 | train:146                      | [  INFO   ] Starting training on measurement 'test'. Depending on the model this might take a while.
⠼ Retrieving model...10:08:47 | resolve_file_path:62           | [  DEBUG  ] 
✅  Model retrieved.
✅  Finished preparing data.
   Training rf: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.95it/s ]                                                                                                                          
10:08:47 | train:168                      | [ SUCCESS ] Training finished successfully.
Traceback (most recent call last):
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/bin/shbdeviceidentifier", line 8, in <module>
    sys.exit(app())
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jo/git/SmartHomeBuddy/device-identifier/shbdeviceidentifier/utilities/logging_utilities.py", line 119, in wrapped
    result = func(*args, **kwargs)
  File "/home/jo/git/SmartHomeBuddy/device-identifier/shbdeviceidentifier/app.py", line 249, in train
    commands.train(model_name=model_name, measurement=measurement)
  File "/home/jo/git/SmartHomeBuddy/device-identifier/shbdeviceidentifier/commands.py", line 174, in train
    if not model.save_path:
AttributeError: 'RandomForest' object has no attribute 'save_path'
```

2022-09-29 08:23 UTC, TB-DevAcc commented
> We currently run into an error when training a model or identifying a device. This error is most likely not caused by this PR, but it exists anyways. I think we should solve it now.
> 
> ```shell
> (.venv) jo@pop-os:~/git/SmartHomeBuddy$ shbdeviceidentifier -d train --measurement "test" "rf"
>    ____               __  __ __               ___          __   __    
>   / __/_ _  ___ _____/ /_/ // /__  __ _  ___ / _ )__ _____/ /__/ /_ __
>  _\ \/  ' \/ _ `/ __/ __/ _  / _ \/  ' \/ -_) _  / // / _  / _  / // /
> /___/_/_/_/\_,_/_/  \__/_//_/\___/_/_/_/\__/____/\_,_/\_,_/\_,_/\_, / 
>                                                                /___/  
> 
> 10:08:46 | start_database:22              | [  DEBUG  ] SHB_HOME: /home/jo/git/SmartHomeBuddy
> 10:08:46 | start_database:23              | [  DEBUG  ] DATA_DIR: /home/jo/git/SmartHomeBuddy/device-identifier/shbdeviceidentifier
> 10:08:46 | start_InfluxDB:404             | [  DEBUG  ] InfluxDB started successfully.
> 10:08:46 | _create_SQLite_tables:241      | [  DEBUG  ] Table 'users' created successfully.
> 10:08:46 | _create_SQLite_tables:244      | [  DEBUG  ] Table 'influxdb' created successfully.
> 10:08:46 | _create_SQLite_tables:247      | [  DEBUG  ] Table 'devices' created successfully.
> 10:08:46 | _create_SQLite_tables:250      | [  DEBUG  ] Table 'context' created successfully.
> 10:08:46 | _get_InfluxDB_connection:259   | [  DEBUG  ] Connected to InfluxDB v2.3.0+SNAPSHOT.090f681737 at localhost:8086.
> 10:08:46 | is_connected:323               | [  DEBUG  ] Databases are connected.
> 10:08:46 | invoke:760                     | [  DEBUG  ] Entering 'train' (args=(), kwargs={'measurement': 'test', 'model_name': 'rf'})
> 10:08:46 | train:141                      | [  DEBUG  ] Querying train data in time range 1970-01-01 00:00:00 - 2022-09-29 10:08:46.748096.
> 10:08:46 | get_influxdb_client:335        | [  DEBUG  ] Creating InfluxDBClient with the following params: url=http://localhost:8086, org=SmartHomeBuddy, token=_MKqs-OXmIYgqg0Q9PwFA3sH_oW2oyX1ZWxnRcUxs7mnpwbHo8PviMIbv6mJnDq2eEIwGnEl2h1rrOMxL7Lc0g==
> 10:08:46 | _from_influxdb:42              | [  INFO   ] Loading data from measurement 'test'. Depending on the size of the data this might take a while.
> ✅  Finished loading data from InfluxDB.
> 10:08:46 | _from_influxdb:53              | [  DEBUG  ] Loaded 13 rows from InfluxDB.
> 10:08:46 | from_database:170              | [  DEBUG  ] Devices: [('Desktop', '192.168.178.41'), ('', '192.168.178.42'), ('Google-Nest-Mini', '192.168.178.44'), ('Google-Nest-Mini', '192.168.178.45'), ('ESP-1DC41C', '192.168.178.47'), ('', '50.16.7.188'), ('fritz.box', '192.168.178.1')]
> 10:08:46 | from_database:175              | [  DEBUG  ] ip_to_label_map: {'192.168.178.41': 'Desktop', '192.168.178.42': '', '192.168.178.44': 'Google-Nest-Mini', '192.168.178.45': 'Google-Nest-Mini', '192.168.178.47': 'ESP-1DC41C', '50.16.7.188': '', '192.168.178.1': 'fritz.box'}
> 10:08:46 | train:146                      | [  INFO   ] Starting training on measurement 'test'. Depending on the model this might take a while.
> ⠼ Retrieving model...10:08:47 | resolve_file_path:62           | [  DEBUG  ] 
> ✅  Model retrieved.
> ✅  Finished preparing data.
>    Training rf: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.95it/s ]                                                                                                                          
> 10:08:47 | train:168                      | [ SUCCESS ] Training finished successfully.
> Traceback (most recent call last):
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/bin/shbdeviceidentifier", line 8, in <module>
>     sys.exit(app())
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
>     rv.append(sub_ctx.command.invoke(sub_ctx))
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/shbdeviceidentifier/utilities/logging_utilities.py", line 119, in wrapped
>     result = func(*args, **kwargs)
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/shbdeviceidentifier/app.py", line 249, in train
>     commands.train(model_name=model_name, measurement=measurement)
>   File "/home/jo/git/SmartHomeBuddy/device-identifier/shbdeviceidentifier/commands.py", line 174, in train
>     if not model.save_path:
> AttributeError: 'RandomForest' object has no attribute 'save_path'
> ```
> 
> It is related to [this line](https://github.com/jo-jstrm/SmartHomeBuddy/blob/ba6657c9e49e15afc39ef9c7e0242b4c62265e61/device-identifier/shbdeviceidentifier/ml_models/random_forest.py#L33). I am not sure how we intended this to work. Probably, we should implement an `else`or some kind of default.

Fixed this and another error relating to a falsely supplied measurement.

2022-09-29 09:44 UTC, jo-jstrm approved these changes

2022-09-29 10:37 UTC, merged