Set up testing and refactor workflows (#81)
jo-jstrm/SmartHomeBuddy pull request #86
Opened 2022-08-30 14:39 UTC by TB-DevAcc

Update main with newest workflows.

2022-09-01 09:26 UTC, jo-jstrm commented
"This pull request quality could be better." Already love Codacy :fire:

2022-09-01 09:34 UTC, jo-jstrm requested changes
Now that we have pipenv, because it is required for the workflows and testing, could we delete our requirements.txt for good?

2022-09-02 10:08 UTC, TB-DevAcc commented
> Now that we have pipenv, because it is required for the workflows and testing, could we delete our requirements.txt for good?

As far as I know you cannot use the Pip file for pip, just pipenv. So if we delete requirements.txt it requires people to either manually install the packages, create their own requierments.txt or use pipenv. To me it does not seem like we are gaining much by deleting it now.

2022-09-02 12:10 UTC, jo-jstrm approved these changes

2022-09-02 12:50 UTC, merged